# Generated by Django 4.1.5 on 2023-01-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pitchingstats_pitchingstatspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battingstats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.TextField(db_column='playerID')),
                ('yearid', models.TextField(blank=True, db_column='yearID')),
                ('stint', models.TextField(blank=True)),
                ('teamid', models.TextField(blank=True, db_column='teamID')),
                ('lgid', models.TextField(blank=True, db_column='lgID')),
                ('g', models.TextField(blank=True, db_column='G')),
                ('ab', models.TextField(blank=True, db_column='AB')),
                ('r', models.TextField(blank=True, db_column='R')),
                ('h', models.TextField(blank=True, db_column='H')),
                ('number_2b', models.TextField(blank=True, db_column='2B')),
                ('number_3b', models.TextField(blank=True, db_column='3B')),
                ('hr', models.TextField(blank=True, db_column='HR')),
                ('rbi', models.TextField(blank=True, db_column='RBI')),
                ('sb', models.TextField(blank=True, db_column='SB')),
                ('cs', models.TextField(blank=True, db_column='CS')),
                ('bb', models.TextField(blank=True, db_column='BB')),
                ('so', models.TextField(blank=True, db_column='SO')),
                ('ibb', models.TextField(blank=True, db_column='IBB')),
                ('hbp', models.TextField(blank=True, db_column='HBP')),
                ('sh', models.TextField(blank=True, db_column='SH')),
                ('sf', models.TextField(blank=True, db_column='SF')),
                ('gidp', models.TextField(blank=True, db_column='GIDP')),
            ],
            options={
                'db_table': 'BattingStats',
                'managed': False,
            },
        ),
    ]
