# Generated by Django 4.1.5 on 2023-01-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_battingstatspost_fieldingstats_fieldingstatspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.TextField(db_column='playerID')),
                ('yearid', models.TextField(blank=True, db_column='yearID')),
                ('teamid', models.TextField(blank=True, db_column='teamID')),
                ('lgid', models.TextField(blank=True, db_column='lgID')),
                ('inseason', models.TextField(blank=True)),
                ('g', models.TextField(blank=True, db_column='G')),
                ('w', models.TextField(blank=True, db_column='W')),
                ('l', models.TextField(blank=True, db_column='L')),
                ('rank', models.TextField(blank=True)),
                ('plyrmgr', models.TextField(blank=True, db_column='plyrMgr')),
            ],
            options={
                'db_table': 'Managers',
                'managed': False,
            },
        ),
    ]
