# Generated by Django 4.1.5 on 2023-02-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={},
        ),
    ]
